.github/workflows/archive-stable-version.yml
.github/workflows/check-if-mergeable.yml
package.json
src/services/index.spec.ts

추가했지롱
* 새벽 4시마다 main에서 release를 머지 합니다
* develop 향한 pr 생성시 테스트가 깨지면 머지를 하지 못합니다

git workflow 추가

---

.github/ISSUE_TEMPLATE/10mm-client-issue-template.md

- 아래와 같은 이슈 템플릿을 생성했습니다.
- 이슈 내용을 입력해주세요

📝 issue template 생성

---

.github/workflows/deploy-chromatic.yml

develop 향한 pr이 머지되었을때도 chromatic deploy 실행 시키기
develop 향한 pr이 머지되었을때도 chromatic deploy 실행 시키기

merge 되었을때도 workflow 동작으로 수정

---

src/components/MonitoringInitializer.tsx

GA 트래킹 ID 수정
- GA 트래킹 아이디를 수정합니다
- Script 태그를 Next 공식문서의 방법으로 수정하였습니다
- https://nextjs.org/docs/messages/next-script-for-ga

[FIX] GA 트래킹 ID 수정

---

src/app/globals.css

button component 를 만드는데 diabled 속성을 가진 버튼이 active 등 클릭 이벤트가 발생하는 현상이 있었어요. 
이를 `pointer-event: none` 을 통해 클릭이 되지 않도록 막았습니다. 
- @우병오빠의 조언

🚑️ button disabled 되면 클릭 안되게 수정

---

src/app/layout.tsx
src/app/select/SelectMissionForm.tsx
src/app/select/page.tsx
src/components/Layout/Header.tsx
src/components/RadioInput.tsx

closed #67 
- header 컴포넌트 디자인 변경
- layout 배경 변경
- 미션등록페이지 [피그마](https://www.figma.com/file/waOSgkTYJKQdMHXnGPlOum/%5BDEV%5D-Design-Guide?node-id=618%3A7162&mode=dev) 기준으로 css변경
- 버튼 컴포넌트 사용

[Design] 미션 등록페이지 디자인 변경

---

src/app/timer/page.tsx
src/components/RadioInput.tsx

- 원활한 회의 시연을 위해 timer 와 complete 페이지를 라우팅합니다. 
- timer > complete 페이지 라우팅연결

[Feat] timer > complete 페이지 라우팅연결

---

src/components/Button/Button.tsx

- 미션등록페이지 버튼 css 수정 
AS-IS
TO-BE
- medium, cta 인경우 position fixed 속성 제거
모든 사이즈 cta 버튼 css에 fixed 포지션이 들어가는게 적절할까요? 아무래도 사이즈가 작아지면 위치는 자유로울거 같아서요 cta large에만 fixed 스타일이 들어가면 좋을 것 같아요

[FIX] 미션등록페이지 버튼 css 수정 

---

src/app/select/MissionRegistration.tsx
src/app/select/page.tsx
src/components/Input/Input.tsx

Design/category UI

---

src/components/Button/Button.tsx

closed #114
버튼이 disabled 일때 opacity대신 filter로 제어할 수 있도록 하였습니도

:art: 버튼 css 수정

---

src/app/select/MissionRegistration.tsx
src/app/stopwatch/page.tsx

미션 등록 페이지에서 입력한 카테고리를, 타이머 페이지에 띄워줄 수 있도록 하였어요. 
- Link -> router 사용
- category를 string으로 받아서 바로 보여주도록 수정 (나중에 바뀔수 있을 것 같음)

[Task] 미션 등록 페이지에서 입력한 카테고리 타이머에서 보여주기

---

src/app/stopwatch/page.tsx

이미지가 돌아가면서 overflow가 일어나는 문제가 있었어요. 
- maxWidth와 overflow : hidden을 설정해주어 수정하였습니다.

🚑️ stopwatch overflow 해결

---

src/app/certification/page.tsx

:art: MaxHeight 수정

---

src/components/Header/Header.tsx

:art: 헤더 색깔 세팅

---

src/app/select/CategoryBottomSheet.tsx
src/app/select/PublicBottomSheet.tsx
src/components/BottomSheet/BottomSheet.stories.tsx
src/components/Header/Header.tsx

:art: 헤더 투명도 설정

---

src/components/Input/Input.tsx

#129 
-  input placeholder의 컬러를 디자인 시스템의 text/placeholder 컬러인 gray.300으로 변경

[Design] placeholder 컬러 변경

---

src/app/select/MissionRegistration.tsx

:lipstick: 카테고리 placeholder

---

src/app/select/MissionRegistration.tsx
src/components/Icon/InputArrowDownIcon.tsx
src/components/Icon/InputCloseCircleIcon.tsx
src/components/Icon/index.tsx
src/components/Input/Input.tsx

- #127 
- Input에 텍스트 입력 시 height가 변경되는 버그 수정
- input에 기본 height값이 없어서 생긴 버그 같습니다. height 기본값을 설정해주었어요.

[Fix] Input Height 설정

---

src/components/Stopwatch/Stopwatch.tsx

🎨 Stopwatch > 1차 MVP 화면에서 변경된 부분 수정 
hotfix

🎨 Stopwatch > 1차 MVP 화면에서 변경된 부분 수정 

---

src/components/Badge/Badge.stories.tsx
src/components/Badge/Badge.tsx

closed #193
* 디자인 시스템 중 Badge 컴포넌트를 추가하였습니다

:art: Badge 컴포넌트 추가

---

src/components/Icon/AlarmIcon.tsx
src/components/Icon/ArrowBackIcon.tsx
src/components/Icon/ArrowDiagonalIcon.tsx
src/components/Icon/ArrowDownIcon.tsx
src/components/Icon/ArrowFowardIcon.tsx
src/components/Icon/CameraIcon.tsx
src/components/Icon/CheckCircleIcon.tsx
src/components/Icon/CloseCircleIcon.tsx
src/components/Icon/CloseIcon.tsx
src/components/Icon/CopyLinkIcon.tsx
src/components/Icon/Icon.stories.tsx
src/components/Icon/InputArrowDownIcon.tsx
src/components/Icon/InputCloseCircleIcon.tsx
src/components/Icon/MenuIcon.tsx
src/components/Icon/NavigationHomeIcon.tsx
src/components/Icon/NavigationMypageIcon.tsx
src/components/Icon/NavigationResultIcon.tsx
src/components/Icon/NavigationUsersearchIcon.tsx
src/components/Icon/NormalClose.tsx
src/components/Icon/PlusCircleIcon.tsx
src/components/Icon/PlusCircleLargeIcon.tsx
src/components/Icon/PlusIcon.tsx
src/components/Icon/RefreshIcon.tsx
src/components/Icon/ShareIcon.tsx
src/components/Icon/TENMMSymbolIcon.tsx
src/components/Icon/index.tsx

closed #43 
icon 에 size props를 추가했습니다. 
viewbox 안건들이고 width height 만 건들었더니 사이즈가 변경되네요. 
스토리북상에서 확인했는데 문제가 되는 상황이 있으시면 이야기해주세요!
만약 이 방법으로 icon size 가 관리 가능하다면 중복으로 생성된 아이콘 제거 필요

[Refactor] icon 사이즈 변경 가능하게 수정

---

src/components/TextArea/TextArea.stories.tsx
src/components/TextArea/TextArea.tsx

closed #205 
1. textArea 컴포넌트를 추가하였어요
1. value를 넘기는 것이 몬가몬가 해요
2. 사용하는 쪽에서 값을 가져올때 ref를 넘겨서 값을 가져오게 할까 고민을 했었어요 (forwardRef, useImperativeHandle)
3. 근데 2번은 너무 복잡해지는 것 같아서 몬가몬가 했어요
4. 더 좋은 방법이 있다면 편하게 말씀해주세요!!

:zap: TextArea컴포넌트 추가

---

src/components/Icon/Icon.mdx
src/components/Icon/index.tsx

close #209 
icon를 svg로 관리하고 있어, 코드상에서 어떤 아이콘이 어떤 name인지 확인하기가 어려웠어요.
storybook의 IconGallery block을 이용하여 아이콘 <-> name 을 매칭 시킨 리스트를 보여줄 수 있도록 하였습니다.
- iconGallery 스토리 추가

🎨 Icon Gallery 스토리 추가

---

src/app/globals.css
src/components/Input/Input.stories.ts
src/components/Input/Input.types.ts
src/components/Input/NormalInput.tsx

✨ 디자인와 다르게 적용되어있던 Input style 수정

---

src/components/Thumbnail/Thumbnail.tsx
src/styles/typography.ts

-  타이포 행간 수정
- Thumbnail selected 상태 border 굵기 수정

디자인 시스템 자잘한 수정사항 반영

---

src/app/mission/[id]/stopwatch/page.tsx
src/hooks/mission/stopwatch/useStopwatch.ts

- 스톱워치 second 계산 훅에서, second가 최대 second에 도달하면 스톱워치 끝으로 판단해서, 스톱워치를 중지시켜요. 
- 끝에 도달하면 자동으로 스톱워치를 멈추고, 이벤트 로그를 보낸 후 인증페이지로 넘어갑니다.

✨스톱워치 자동 종료 기능 추가

---

src/app/mission/[id]/stopwatch/layout.tsx
src/app/mission/[id]/stopwatch/modals.tsx
src/app/mission/[id]/stopwatch/page.tsx

- 헤더의 뒤로가기 버튼을 클릭했을 때 예외를 처리하였습니다. 
- 10분 전에 끝내기 버튼을 클릭했을 떄 예외를 처리하였습니다. 
- 각각의 상황에 맞게 이벤트 로그를 보내도록 하였어요. 
- 사용하는 모달을 따로 `modals.tsx`라는 파일에 분리하여 import 하여 사용하였습니다.

✨ 타이머 예외 케이스 대응 > 타이머 상세 페이지

---

src/app/mission/[id]/stopwatch/page.tsx
src/constants/router.ts

🚑️ 미션 인증 페이지 url이 잘됫 되어있던 이슈

---

src/components/Header/IconHeader.tsx

IconHeader 에서 onIconClick props가 onClick 이벤트로 등록 안되어 있던 곳 등록

[FIX] IconHeader 

---

src/app/mission/[id]/stopwatch/layout.tsx
src/app/mission/[id]/stopwatch/modals.tsx
src/app/mission/[id]/stopwatch/page.tsx

closed #259 
- 스톱워치 페이지에서 뒤로가기 동작을 하는 경우 뒤로가기 버튼 눌렀을 때와 같은 동작이 일어나도록 하였습니다. 
- 페이지에 들어가자마다 `useEffect`가 실행되기 전 뒤로가기를 수행하면 뒤로가지긴 하는데, 기획상 큰 문제는 아닌것 같습니다.

✨ 스톱워치 뒤로가기 동작 제어 

---

src/app/mission/[id]/detail/modify/MissionModify.tsx
src/app/mission/[id]/detail/modify/page.tsx
src/app/mission/[id]/detail/page.tsx
src/constants/router.ts

- @wade3420 가 만들어주신 Menu 컴포넌트로 미션 상세 페이지 -> 미션수정, 미션 삭제로 라우팅 했습니다.
- 어제 논의한 apis 컨벤션 작업이 아직 미완인 것 같아, API 관련 작업은 TODO로 주석 달아놓았습니다.

[Feat] 미션 상세 페이지 라우팅

---

src/apis/schema/feed.ts
src/apis/schema/member.ts
src/apis/schema/mission.ts
src/apis/schema/pageable.ts
src/apis/schema/record.ts
src/apis/schema/summary.ts

closed #274 
- 서버 스키마 정의
- Request, Response에 관련된 스키마는 제외

✨ 서버 스키마 정의

---

src/app/guest/mission/new/page.tsx
src/app/guest/mission/stopwatch/page.tsx
src/app/mission/[id]/record/page.tsx
src/app/mission/[id]/stopwatch/index.hooks.ts
src/app/mission/[id]/stopwatch/modals.tsx
src/app/mission/[id]/stopwatch/page.tsx
src/components/Header/Header.tsx
src/constants/eventLog.ts

🚚 이벤트 로그 상수화

---

src/app/mission/[id]/history/[historyId]/HistoryThumbnail.tsx
src/app/mission/[id]/history/[historyId]/MissionDuration.tsx

https://www.figma.com/file/waOSgkTYJKQdMHXnGPlOum?node-id=1535:49823&mode=dev#657528806
미션내역 상세  MissionDuration 디자인수정

:lipstick: MissionDuration 디자인수정

---

src/apis/mission.ts
src/apis/schema/mission.ts
src/app/home/MissionList.tsx
src/app/home/home.hooks.ts
src/components/SnackBar/SnackBar.stories.tsx

- 홈화면에서, 인증이 필요한 미션이 있는 경우 토스트 박스를 띄웁니다.

인증화면에서 이탈했을 경우 홈화면 처리

---

src/instrumentation.ts
src/msw/MSWInitComponent.tsx
src/msw/handlers/mission.ts

qa 를 위해서 develop 배포환경에서 msw가 동작하게 설정하였습니다. 
(배포한 상태에서 동작하는  것 또한 확인)
NEXT_PUBLIC_MSW_EBABLE 환경변수를 vecrel 에 설정했습니다 (production 빼고 preview와 devlopment 에 설정함)

[Chore] msw deploy 설정

---

src/components/SnackBar/IconSnackBar.tsx
src/components/SnackBar/SnackBar.stories.tsx
src/components/SnackBar/SnackBar.tsx
src/components/SnackBar/SnackBar.types.ts
src/components/SnackBar/SnackBarProvider.tsx
src/components/SnackBar/TextButtonSnackBar.tsx

closed #293
- variant: 'text-button', variant: 'icon' 상황에서 onClick 이벤트 발생시 스낵바 버튼 사라지게 하였습니다.

[Task] 스낵바 버튼 클릭하면 화면에서 사라지는 기능

---

src/app/mission/[id]/stopwatch/page.tsx
src/hooks/mission/stopwatch/useStopwatchStatus.ts
src/styled-system/tokens/keyframes.css
src/styled-system/tokens/tokens.d.ts
src/styles/motion.ts

closed #302 
- 타이머 페이지 텍스트 간격 수정
- 타이머 페이지 문구 수정
- 이전 step 저장 오류가 있어 수정
- 문구 등 부드럽게 나타나도록 애니매이션 추가
- 애니매이션은 추후 앱에서 테스트 후 어색하다면 제거할 예정입니다. 
-

[Design] 타이머 페이지 디자인 수정사항 반영

---

src/app/home/MissionList.tsx
src/app/home/ProfileList.tsx

- 홈탭 메인화면 title-bar 여백 및 글자 크기, 아이콘 크기 수정됨
- 프로필 리스트 영역 하단 여백 수정됨

[Design] 홈탭 디자인 수정사항 반영

---

src/apis/mission.ts
src/app/home/home.hooks.ts
src/app/mission/[id]/detail/MissionHistoryTab.tsx
src/app/mission/[id]/detail/modify/page.tsx
src/app/mission/[id]/detail/page.tsx
src/constants/mission.ts

close #172 
- 미션 삭제 api
- 미션 생성 api
@JUNOSHON 가 구현하신 것 토대로 api 이어보았습니다 문제되는 것 있으면 리뷰주세요!

[Task] 미션 삭제 / 수정 api 

---

src/components/Banner/Banner.stories.ts
src/components/Banner/Banner.tsx
src/components/Banner/Banner.types.ts
src/components/Banner/CardBanner.tsx
src/components/Banner/GraphicBanner.tsx
src/components/Banner/ListBanner.tsx

- @wade3420 가 만들어둔 ListBanner를 통해 세가지 타입의 Banner를 디자인 시스템에 추가하였습니다

[Design] banner 컴포넌트 추가

---

src/apis/auth.ts
src/apis/member.ts
src/apis/record.ts
src/apis/schema/record.ts
src/apis/schema/upload.ts
src/app/mypage/Profile.tsx
src/app/mypage/ProfileContent.tsx
src/app/mypage/page.tsx
src/app/mypage/profile_modify/page.tsx
src/components/Thumbnail/NullableThumnail.tsx
src/hooks/useImage.ts
src/msw/handlers/index.ts
src/msw/handlers/member.ts

#173 
- 프로필 업로드 api 
- 프로필 업로드 완료 api
- 조회 api (목 api)
- 종료 미션 리스트 버튼 제거
- 조회 api 는 아직 구현이 되지 않아서 백엔드 구현되면 바로 붙이겠습니다.

[Task] my page 수정 api

---

src/utils/event/gtag.ts
src/utils/event/hotjar.ts
src/utils/event/index.ts
src/utils/event/mixpanel.ts

관련 슬랙
https://depromeet14th.slack.com/archives/C065F2Z6DC2/p1705477139537019
- event logger id 가 없는 경우 등록하지 않고 등록된 evet logger가 없다면 dev와 동일하게 작동하도록  했습니다

:bug: event logger id 가 없는 경우 등록하지 않는다

---

src/app/auth/signup/page.tsx
src/app/mission/[id]/detail/MissionHistoryBanner/MissionHistoryBanner.tsx
src/components/Input/NormalInput.tsx
src/constants/mission.ts

[Qa] 스타일 수정사항 반영

---

src/apis/mission.ts
src/apis/schema/mission.ts
src/app/home/MissionList.tsx
src/app/home/home.hooks.ts
src/app/mission/[id]/detail/MissionHistoryBanner/MissionHistoryBannerApi.tsx

- 홈탭에서 인증 필요 미션이 있을 경우 클릭하면 이동되도록 수정하였습니다.

✨ 인증 필요 미션 홈탭에서 체크

---

src/app/mission/[id]/stopwatch/index.hooks.ts
src/app/record/[id]/page.tsx
src/hooks/mission/stopwatch/useStopwatch.ts

[FIX] 마이너 변경사항 적용

---

src/app/home/AppBar.tsx
src/app/mypage/MenuList.tsx

안쓰이는 부분 삭제

---

src/apis/instance.api.ts
src/app/global-error.tsx

> The root app/error.js boundary does not catch errors thrown in the root app/layout.js or app/template.js component.
>
> To specifically handle errors in these root components, use a variation of error.js called app/global-error.js located in the root app directory.
next 공식문서 참고하여 global-error.tsx 파일을 추가합니다.
https://nextjs.org/docs/app/building-your-application/routing/error-handling

:sparkles: global-error.tsx 페이지 추가

---

src/app/home/MissionList.tsx
src/app/mission/[id]/detail/modify/MissionModify.tsx
src/app/mission/new/MissionRegistration.tsx

- 미션 내역 생성에서 공개범위 input 보이게한다.
- 수정되어야할 QA
https://www.notion.so/depromeet/QA-e4d961b8f6ce4052ad0b12450da0801f?pvs=4
-  미션 내역 생성에서 공개범위 input 보이게한다.
- 미션 리스트에서 content 보여주고 있던 것을 name을 보여준다. 
- 미션 생성 content 옵셔널 (기획과 다른 부분 수정)

[FIX] 미션 생성, 수정

---

src/components/Thumbnail/Thumbnail.tsx
src/components/Thumbnail/Thumbnail.types.ts

- hotfix: thumbnail image src null 들어가는 이슈 해결
- thumnail이 없는 유저의 경우 home에 들어갔을 때 error 발생

hotfix: thumbnail image src null 들어가는 이슈 해결

---

next.config.js

https://depromeet14th.slack.com/archives/C06C1271G56/p1705931615954109
CDN 도메인 주소 추가했습니다.

chore : image cdn 도메인 추가

---

src/app/mypage/profile_modify/page.tsx

[Fix] Typo 수정

---

src/app/mypage/ProfileContent.tsx

https://depromeet14th.slack.com/archives/C06C1271G56/p1705939457355649?thread_ts=1705931615.954109&cid=C06C1271G56
백엔드에서 처리해주기로 소통되어 로직 제거합니다.
addDummyQuery 로직 제거

chore : addDummyQuery 로직 제거

---

next.config.js
src/apis/createQueryKeyFactory.ts
src/apis/member.ts
src/apis/mission.ts
src/apis/record.ts
src/app/mypage/ProfileContent.tsx
src/app/mypage/profile_modify/page.tsx
src/hooks/query/getQueryKey.ts
src/hooks/query/index.ts

Reverts depromeet/10mm-client-web#359

Revert "배포용 pr"

---

next.config.js
src/apis/createQueryKeyFactory.ts
src/apis/getQueryKey.ts
src/apis/member.ts
src/apis/mission.ts
src/apis/record.ts
src/app/mypage/ProfileContent.tsx
src/app/mypage/profile_modify/page.tsx
src/hooks/query/index.ts

Reverts depromeet/10mm-client-web#360

Revert "Revert "배포용 pr""

---

src/app/mission/[id]/detail/MissionHistoryTab.tsx
src/app/mission/[id]/stopwatch/index.hooks.ts
src/app/mission/[id]/stopwatch/page.tsx

- 스톱워치 페이지에서 뒤로가기 동작을 커스텀 했더니, 히스토리 스택이 잘 못 쌓여
-  미션 내역 -> 스톱워치 -> 미션 내역으로 무한 뒤로가기가 일어나는 현상이 있었어요. 
- 뒤로가기 스택을 쌓는 부분을 열심히 고민하여 수정 / 잘 동작되는 것 확인
- `취소`버튼을 누를 때 동작을 따로 설정해주어야해서 모달을 하나 더 만들었습니다.

⚡️ 뒤로가기 동작 수정

---

src/app/home/home.hooks.ts
src/app/mission/[id]/detail/MissionHistoryTab.tsx
src/app/mission/[id]/detail/page.tsx
src/components/SnackBar/TextButtonSnackBar.tsx

closed #378 
closed #375 
- 인증 필요 / 진행중 상태의 미션인 경우에 같은 스낵바 메시지를 보여주고 있었어요. 
디자인에 맞게 다른 문구를 보여주도록 수정하였습니다. 
- 인증 필요의 경우 인증이 가능한 시간이 정해져 있습니다. (서버에서 값을 내려줌) 가능한 시간을 스낵바에서 줄어드는 타이머로 확인할 수 있도록 하였어요. (스크린샷 참고)

[Fix] 홈화면 인증필요/진행중 상태 스낵바 기능 수정

---

src/app/mypage/MenuList.tsx
src/app/mypage/MyProfile.tsx
src/app/mypage/page.tsx
src/app/mypage/profile_modify/page.tsx
src/app/mypage/setting_and_private/page.tsx
src/hooks/useImage.ts

크리티컬하다고 생각하는 문제와 빠르게 고칠수있는 문제 고쳐보았습니다
- 마이페이지 > 레벨부분 선택이 될것 처럼 보이는데 선택 후 동작이 없어요
- 마이페이지 > 설정 버튼이 우측으로 치우쳐 있어요
- 마이페이지 > 설정 버튼 누르고 설정 상세로 들어갔을때 탭이 나와요
- 수정하기 버튼 누르고 로딩시간이 길면 두번 누를 수 있음
- 수정하기 로직중 확장자 추출 로직 변경 ( 추후에 백엔드에서 내려주는 정보로 변경 예정 )
- 설정페이지에서 Appbar 제거 
- 피그마와 다르게 구현된 부분 수정
- 레벨 배너 클릭시 레벨 가이드 화면으로 라우팅
- 수정시 로딩 스피너 노출

[HOFIX] 마이프로필 QA 반영

---

src/app/layout.tsx

chore: 웹뷰 핀치줌 막기

---

src/app/auth/login/page.tsx

chore: 아이디 로그인 제거

---

src/app/template.tsx

closed #401
애니메이션 처리가 완성도가 낮아 임시로 제거합니다

chore: 웹 애니메이션 임시 제거

---

src/app/layout.tsx

chore: 놓친 메타태그 추가

---

src/app/globals.css

closed #412 
* 버튼 클릭시 나오는 하이라이트 제거 
* 글자들 선택 안되게 막기
* 링크를 오래 눌렀을때 액션 막기

chore:css웹뷰세팅  추가

---

src/app/guest/mission/stopwatch/page.tsx
src/app/mission/[id]/stopwatch/page.tsx
src/components/Stopwatch/Stopwatch.stories.tsx
src/components/Stopwatch/Stopwatch.tsx

미션 진행중 미션이름 보여주기
관련 테스크 : https://www.notion.so/depromeet/UI-9898d297a3c04838a7dfbf9ae1897371?pvs=4
미션 진행중 미션이름 보여주기
게스트 버젼에서는 카테고리로 보여줍니다.

[FIX] 미션 진행중 미션이름 보여주기

---

src/apis/record.ts
src/app/home/FollowMissionList.tsx
src/app/mission/[id]/detail/MissionCalender/MissionCalendar.tsx
src/app/mission/[id]/detail/MissionCalender/MissionCalendar.utils.ts
src/app/mission/[id]/detail/MissionCalender/MissionCalendarItem.tsx
src/app/mission/[id]/detail/MissionHistoryTab.tsx
src/app/mission/[id]/detail/MissionStartButton.tsx
src/app/mission/[id]/detail/page.tsx
src/app/mission/[id]/follow/page.tsx
src/app/record/[id]/follow/page.tsx
src/constants/router.ts

팔로우(친구) 미션 상세페이지
친구의 미션 상세페이지 미션 페이지에서 미션 시작하기 버튼과 수정하기 버튼들을 삭제하였습니다.
미션 상세 페이지에서 미션시작하기 버튼을 컴포넌트로 나누었습니다. 로직상문제없는지 확인해주세요 @sumi-0011 
[feat : MissionStartButton.tsx 컴포넌트 분리](https://github.com/depromeet/10mm-client-web/commit/2982f55e42c6c327740c278d149480ef2ed29d46)

[Task] 팔로우(친구) 미션 상세페이지

---

src/app/home/FollowSummary.tsx
src/app/profile/[id]/ProfileContent.tsx
src/app/record/empty/page.tsx

[Hotfix] 팔로우 팔로잉

---

src/app/home/FollowMissionList.tsx
src/app/home/MissionEmptyList.tsx
src/app/home/MissionInnerList.tsx
src/app/record/empty/page.tsx

fix : 미션 내역 없을 때  완료 버튼 없애기

---

src/hooks/useAuth.ts
src/services/auth/actions.ts

관련 슬랙 : https://depromeet14th.slack.com/archives/C065F2Z6DC2/p1706521049354469
.env 에 추가한뒤 실행
NEXT_PUBLIC_ACCESS_TOKEN={엑세스토큰}
NEXT_PUBLIC_REFRESH_TOKEN={리프레싀토큰}

feat : 개발환경에서 env로 토큰을 주입할 수 있게 한다

---

src/app/auth/nickname/page.tsx
src/app/guest/mission/new/page.tsx
src/app/level/guide/page.tsx
src/app/mission/[id]/detail/MissionStartButton.tsx
src/app/mission/new/MissionRegistration.tsx
src/app/mypage/profile_modify/page.tsx
src/components/Button/Button.tsx
src/components/Graph/FutureLevelGraph.tsx

마이페이지 UI 의 변경과 더불어 아래의 오타도 수정했습니다.
- level/guide/page.tsx 의 오타 수정
- mission/new/MissionRegistration.tsx 의 input 플레이스 홀더 오타 수정
-  아래 스크린샷 중 왼쪽 사진은 구현중인 사진이고, 오른쪽은 Figma의 변경된 UI 입니다.
- 저장버튼을 하단에 붙이는 걸 어떻게 해야 좋을지 여쭙고 싶습니다!

[Fix] 마이페이지 UI 변경사항 적용

---

src/app/home/FollowContent.tsx
src/app/home/FollowList.tsx
src/app/home/UserProfile.tsx
src/app/page.tsx
src/app/search/page.tsx
src/components/BottomSheet/BottomSheet.tsx
src/components/ListItem/Follow/FollowerItem.tsx
src/components/ListItem/Follow/FollowingItem.tsx
src/components/SnackBar/TextButtonSnackBar.tsx

- 닉네임 검색에서 프로필 안보임
- 친구 프로필 구경하다가 뒤로가기 누르면 미션탭의 내 미션으로 회귀하는 동선 수정 필요
- 스넥바 컴포넌트 상하좌우 마진 체크
- 디자인시스템 : 바텀시트 핸들러 숨김 처리
- query parameter 로 팔로우 id 상태 관리 
- ### 🙏 여기는 꼭 봐주세요!
https://github.com/depromeet/10mm-client-web/assets/68339352/dfb9b324-d655-4f10-bca8-d946f8485419

[Fix] QA 사항 적용

---

src/app/auth/login/page.tsx

aos 앱에서 무슨무슨 경우세 카카오 앱 로그인이 불가능해서 일단 빼놓습니다

:bug: 안드로이드 앱 카카오 로그인 버그 수정

---

src/app/auth/login/page.tsx
src/app/global.d.ts
src/constants/common.ts

:art: Aos 카카오 로그인 수정

---

src/app/auth/login/page.tsx
src/app/global.d.ts
src/constants/common.ts

aos 카카오 로그인 수정본 놓친것 바로 배포

---

src/app/auth/login/page.tsx

:art: Rollback 카카오 로그인 안드로이드

---

src/apis/auth.ts
src/app/auth/login/page.tsx

closed #446
앱에서 토큰 값을 같이 가져와 업데이트를 쳐줍니다
현재는 별도의 api로 분리되어 있지만
추후에는 socialLogin에 붙여버릴 예정입니다

feat: 로그인시 디바이스 토큰 업데이트 

---

src/apis/instance.api.ts
src/app/error.tsx
src/app/template.tsx
src/hooks/useAuth.ts
src/utils/appEnv.ts

close #473 
서버에서 401 error가 뜨면 로그인 페이지로 라우팅합니다.
로컬 환경에서만 로컬스토리지 token으로 로그인하게 합니다

[Hofix] 서버에서 401 error가 뜨면 로그인 페이지로 라우팅합니다.

---

src/apis/instance.api.ts
src/app/error.tsx
src/app/template.tsx
src/hooks/useAuth.ts
src/utils/appEnv.ts

Reverts depromeet/10mm-client-web#474

Revert "[Hofix] 서버에서 401 error가 뜨면 로그인 페이지로 라우팅합니다."

---

src/apis/instance.api.ts

- revert hofix/401-error
웹뷰 로그인 상태에서 영향이 가지 않을 것이라 예상되는 아래의 두개 기능은 그대로 가져가겠습니다
- axios withCredentials : true 설정 
- 401에러인 경우 로그인 페이지로 라우팅

[Revert] "Merge pull request #479 from depromeet/hofix/401-error" 

---

src/constants/eventLog.ts
src/hooks/mission/stopwatch/useStopwatch.ts
src/utils/storage/progressMission.ts

- 10분을 완료하는 사람들을 기록하기 위한 이벤트를 추가하였습니다. 
- 완전히 정확한 데이터는 아닐 수 있어요 😉

[Feat] 10분 기록시 체크 이벤트 등록

---

src/app/layout.tsx

:art: 배경색 bg.surfase3 추가

---

src/app/level/guide/GrowthLevel.tsx
src/components/Motion/StaggerWrapper.tsx

:art: 스크롤바 이슈 수정

---

src/apis/feed.ts
src/apis/getQueryKey.ts
src/app/feed/FeedItem.tsx
src/app/feed/FeedList.tsx
src/app/feed/page.tsx
src/components/ListItem/ProfileListItem.tsx
src/constants/navigation.ts
src/constants/router.ts
src/msw/handlers/feed.ts
src/msw/handlers/follow.ts
src/msw/handlers/index.ts

- feed tab 구현
- feed api 추가
- feed tab 구현
리액션 작업에 feed tab 이나 feed item UI 가 필요하시면 이 PR 머지 후에 task/feed 에서 작업하시면 될 것 같아요 @sumi-0011

[FEAT] feed tab 구현

---

src/apis/instance.api.ts
src/app/layout.tsx

미션 수정 페이지에서 새로고침시 일어나는 에러 수정
- Suspense 없이 useSuspenseQuery를 사용해서 나는 에러였습니다. 
- root 에서 Suspense 로 감싸도록 수정하였습니다
수정 후 재현 안되는 모습
https://github.com/depromeet/10mm-client-web/assets/68339352/348dedf5-d4c5-4dbf-859f-234fb41be857

[FIX] 미션 수정 페이지 리프레시 오류 fix

---

src/app/home/FollowList.tsx
src/app/home/MissionList.tsx

closed #522 
- 1. ‘친구 추가하는 곳이 어딘지 모르겠다’ ->  프로필 옆에 작은 플러스 버튼 추가
- 2. ‘미션 추가가 바로 보이지 않는다’ -> 아이콘 색 Primary로 변경

[Feat] 홈화면 피드백 반영

---

src/components/Banner/CardBanner.tsx

closed #465 
- CardBanner 컴포넌트의 style이 변경되었습니다. 
- 디자이너 분들이 수치스럽다고 하셨기 때문에 변경해보았습니다.

[Style] card banner border fix!

---

src/apis/member.ts
src/app/mypage/withdrawal/page.tsx

회원 탈퇴 시 유저네임을 보낼 필요가 없어져서 제거하였습니다. 
관련 슬랙 : https://depromeet14th.slack.com/archives/C06C1271G56/p1707277108851489

fix : 회원탈퇴 api 수정

---

src/app/feed/FeedList.tsx
src/app/feed/page.tsx
src/app/mypage/ProfileFeedList.tsx
src/app/mypage/page.tsx
src/app/profile/[id]/ProfileContent.tsx
src/app/profile/[id]/page.tsx
src/components/BottomDim/BottomDim.tsx

- 피드탭과 마이프로필, 팔로우 프로필에서 bottom dim 다르게 적용
- 팔로우 팔로잉 피그마와 같게 폰트적용
- 피드탭, 프로필 피드탭 empty 화면 추가

[FIX] 마이너한 디자인 수정사항

---

src/app/mypage/page.tsx

:art: 핫픽스 수정 => navigator없을시 에러 발생

---

src/components/BottomSheet/BottomSheet.tsx
src/components/Header/HeaderBase.tsx

fix : bottomsheet zIndex 수정

---

src/app/guest/mission/success/page.tsx
src/app/record/success/page.tsx

fix : 확인 버튼 zIndex 수정

---

src/app/layout.tsx
src/app/mypage/profile_modify/page.tsx
src/components/Menu/MenuContent.tsx
src/components/Menu/MenuItem.tsx

- 프로필 수정 페이지 레이아웃
- 메뉴 컴포넌트 호버 css
https://depromeet14th.slack.com/archives/C06J5C4LFM4/p1707794766551999
https://depromeet14th.slack.com/archives/C06J5C4LFM4/p1707795691733769

[Fix] 디자인 qa 반영

---

src/app/mypage/page.tsx

fix : share Url 변경

---

src/apis/instance.api.ts

 fix : 401 redirect 로직 제거

---

src/app/mission/[id]/follow/page.tsx
src/app/result/finished/[id]/page.tsx
src/components/MissionDetail/MissionHistoryTabLayout.tsx

나의 미션상세에서만 보이던 미션통계를 종료미션, 팔로우의 미션 상세에서도 볼 수 있게한다

feat : 미션 통계 탭 추가

---

src/apis/feed.ts
src/apis/getQueryKey.ts
src/app/feed/FeedItem.tsx
src/app/feed/FeedList.tsx
src/app/feed/FeedSection.tsx
src/app/feed/page.tsx
src/hooks/useShowGuide.ts

- 전체 피드 기능을 추가하였어요. 
- 전체 피드 API 연결
- 팔로워의 피드가 하나도 없는 경우에 전체 피드를 먼저 보여주도록 하였어요.
- 전체 피드 기능이 추가되었다는 안내 문구를 추가하였어요 (실행시 단 한번만 발생)

[Feat] 전체 피드 기능 추가

---

src/components/NotificationSnackBar/NotificationSnackBarProvider.tsx
src/components/SnackBar/SnackBarProvider.tsx

fix : 스낵바 시간 감소

---

public/images/banner/graphic-bg-gradient.svg
src/app/auth/login/page.tsx
src/app/result/OverallStatus/MissionList.tsx
src/app/result/OverallStatus/MissionSection.tsx
src/components/Banner/GraphicBanner.tsx
src/components/MissionList/ReactionLinkItem.tsx
src/components/Thumbnail/Thumbnail.tsx

[Fix] QA 수정사항 반영

---

src/app/feed/FeedItem.tsx

fix : FeedItem 텍스트 클릭시 라우팅하도록 변경

---

src/components/Banner/GraphicBanner.tsx

hotfix: 딤드 이미지 수정

---

src/app/mission/[id]/stopwatch/page.tsx

발표용으로 임시로 시간 확인부분 제거

---

src/app/home/home.hooks.ts

시간이 10분이 안되었고 인증이 안되었다고 뜨는 부분 임시 주석 처리

---

src/app/home/home.hooks.ts

Reverts depromeet/10mm-client-web#607

Revert "시간이 10분이 안되었고 인증이 안되었다고 뜨는 부분 임시 주석 처리"

---

src/app/mission/[id]/stopwatch/page.tsx

Reverts depromeet/10mm-client-web#606

Revert "발표용으로 임시로 시간 확인부분 제거"

---

src/app/record/[id]/detail/MissionRecordDetail.tsx

closed #613 
- 일지 줄바꿈 처리를 style를 이용해 처리
- 참고 : https://offbyone.tistory.com/326

일지 줄바꿈 처리 

---

src/utils/storage/progressMission.test.ts

- 진행중인 미션의 데이터를 storage에서 가져오는 로직을 테스트하였어요.

[Test] Progress Mission Data Get Logic Test

---

src/app/record/[id]/detail/MissionRecordDetail.tsx

- 참고 스레드 : https://10mm-hq.slack.com/archives/C06NDAMBZQT/p1710789105854579

숨겨진 다락방 이슈 해결

---

src/app/feed/FeedItem.tsx

피드 일지에 줄바꿈 적용

---

.github/CODEOWNERS

chore : 리뷰어 변경

---

src/utils/storage/progressMission.test.ts
src/utils/storage/progressMission.ts

- 오늘 진행 미션이 아니면 삭제하는 로직 삭제
- 이에 맞춰 테스트 코드 수정
- 오늘 시작한 미션이 아니여도 데이터가 남아있는지 체크

fix: 오늘 시작 미션이 아니여도 삭제하지 않음

---

src/components/Chip/Chip.stories.ts
src/components/Chip/Chip.tsx

- 디자인 시스템 Chip 컴포넌트 추가
- 따로 크게 신경쓸 건 없었습니다
https://github.com/depromeet/10mm-client-web/assets/49177223/b04faa2a-5e8a-4f42-a29c-5be956d6c407

chip component 추가 및 스토리북 적용

---

src/components/ErrorPage.tsx

서버 배포 이슈로 인한 점검 시간 변경
- 하루 더 연장...

fix: 점검 시간 변경

---

src/components/ErrorPage.tsx

- 점검 시간 연장
- 백엔드 배포 이후 안정화 되는대로 ErrorPage 컴포넌트 return null로 변경예정

fix: 점점 시간 변경

---

src/pages/_app.page.tsx

fix: Error Page 주석
