.eslintrc.js
.prettierignore

styled-system 을 eslint ignore 해주어야하는데 파일 경로 설정이 제대로 들어가지 않았는지 lint가 적용된채로 git에 올라오고 있었습니다.
- ignorePatterns
- .prettierignore 추가

styled-system 파일 eslint ignore 안되는 버그 수정

---

.storybook/preview.ts
src/components/Layout/Header.stories.ts

- 크로마틱 빌드 이슈 해결
- storybook build 가 안됨을 확인
- storybook Header Component storybook 실행 버그 수정
`import { useRouter } from 'next/navigation';` 를 이용한 컴포넌트를 스토리북에서 사용하면 발생하는 오류였습니다. 
@준호 가 말한것 처럼 모든 스토리에 넣으면 불편하니 storybook 세팅 중 하나인 `preview.ts` 파일을 수정해서, 모든 스토리에 공통적으로 포함되게 하였어요. 
- https://github.com/vercel/next.js/discussions/50068

[Fix] Storybook build error fix

---

.vscode/settings.json

- #92 
- .vscode/settings.json의 fixAll.eslint와 fixAll.stylelint 값을 "explicit"로 수정했습니다.
- [Visual Studio Code 1.85](https://code.visualstudio.com/updates/v1_85#_code-actions-on-save-and-auto) 버전부터 true가 "explicit"로 수정되었습니다.
- https://stackoverflow.com/questions/77637621/vscode-workspace-settings-change-on-its-own

[Chore] .vscode/settings.json 파일 수정

---

src/app/auth/nickname/page.tsx

1. 버튼 위치가 피그마랑 다른데 버튼 컴포넌트 건드려야 해서 따로 가져갈게요
2. api 붙이는건 후속으로 해버릴게요

:art: 닉네임페이지 ui 작업

---

src/app/auth/nickname/page.tsx
src/app/mission/new/MissionRegistration.tsx
src/components/Input/Input.stories.ts
src/components/Input/Input.tsx
src/components/Input/Input.types.ts
src/components/Input/NormalInput.tsx

디자인 시스템 이전에 @JUNOSHON 이 만들어준 `Input` 컴포넌트를 현재 디자인 시스템에 맡게 `vairant`를 통해 분기할 수 있도록 하였어요. 
close #218 
- `Input` 파일에 있던 내용이 `NormalInput` 파일로 이동되었어요. 
- 기존에 있던 `icon` props는 우측 아이콘이 고정되어있음에 따라 제거하였어요. 
- 
- 기존에 Input 내부에서 `useState`를 통해 inputValue를 관리하고 있었는데, state로 관리하지 않아도 필요한 기능을 구현할 수 있어 제거하였습니다 . (+ 상단의 'use client'도 삭제하였어요)

♻️ Input type='normal' 컴포넌트 리팩토링

---

src/app/home/AppBar.tsx
src/app/home/MissionList.tsx
src/app/layout.tsx
src/app/page.tsx
src/components/BottomDim/BottomDim.tsx

closed #232 
- 홈탭 메인 scroll guide 추가
- 홈탭 메인에 bottom-dim 추가
- 홈탭 상단 app bar position 상단에 배치
-  bottom-dim의 경우 다른 페이지에서도 사용하기 때문에 `components` 폴더에 구현

🎨 홈탭 디자인 가이드 수정 적용

---

src/components/Header/HeaderBase.tsx
src/components/Header/IconHeader.tsx

- Header 컴포넌트 text button 인경우 피그마와 다르게 구현된 부분 수정
오른쪽 element의 padding값이 달라서 수정해 주었어요
- 피그마
- 구현되어있던 Header 컴포넌트
오른쪽 element의 padding값이 달라서 수정 버튼인 경우 header wrapper 의 padding 안넣고 버튼 컴포넌트의 padding 만으로 간격 조절
수정본
https://www.figma.com/file/waOSgkTYJKQdMHXnGPlOum/%5BDEV%5D-Design-Guide?node-id=591%3A3866&mode=dev

[Design] Header 컴포넌트 text button 인경우 피그마와 다르게 구현된 부분 수정

---

src/components/Badge/Badge.stories.tsx
src/components/Badge/Badge.tsx

closed #255 
- Badge 컴포넌트에 `variant` 라는 props를 추가하였어요. 
- 그리고 기존 Badge에 호환되게 `line`이라는 variant를 기본값으로 설정하였습니다. 
- color + variant='solid'의 경우에는 color 마다 조합을 해주어야해서, `compoundVariants`를 사용하였습니다.

🎨 badge 새로운 타입 추가

---

src/components/Button/Button.tsx
src/components/Input/Input.tsx
src/components/Input/Input.types.ts
src/components/Input/NormalButtonInput.tsx
src/components/Input/NormalInput.tsx
src/utils/getBorderColor.ts

close #254 
- 01/01 디자인 시스템의 변경된 사항인 Input variant:normal-button 추가
- Input 우측 하단의 글자수의 컬러를 몇 자를 입력하든 text/tertiary 로 통일했습니다.
-  secondary 버튼의 disabled 상태 시 css가 brightness(0.4) 로 되어있어서 0.9로 수정했습니다! 다른 페이지에서 disabled인 small 버튼을 사용하는 곳이 없는 것 같기도 하고, 디자인 팀에서도 disabled 버튼을 컬러 코드가 아닌 퍼센테이지로 관리하는 게 좋겠다고 하셔서 수정해봤어요.
- Input 컴포넌트에 normal-button 케이스를 추가하니까 기존 normal 인풋이 에러가 나네요...TS 에 무지한 저를 도와주시면 감사합니다 😭

[Feat] Input variant normal-button 추가

---

src/app/mission/[id]/stopwatch/page.tsx
src/app/mission/[id]/stopwatch/time.hooks.ts
src/constants/storage.ts
src/hooks/useInterval.ts

✨ 스톱워치 시간 저장 (주기적 / 웹 이탈 시)
- 주기적으로 시간을 저장하기 위해 setInterval로 만든 useInterval 훅을 이용했어요. 
- 웹 이탈 시에 시간을 저장하기 위해 `Document: visibilitychange 이벤트`를 사용하였습니다. 
- 웹 이탈 시 시간 저장하는 부분이 웹/앱에서 이상이 없다면 `setInterval`는 제거 예정입니다. 
- storage key를 한 곳에서 관리하기 위해 `storage.ts` 상수 파일을 생성하였어요. 
> https://velog.io/@rkd028/React-Javascript-%EB%92%A4%EB%A1%9C%EA%B0%80%EA%B8%B0-%EB%A7%89%EA%B8%B0
에서 발생한 2번째 이슈가 동일하게 발생합니다 ㅜ 해결은... 네...못했어요

✨ 스톱워치 시간 저장 (주기적 / 웹 이탈 시)

---

src/app/mission/[id]/detail/modify/page.tsx
src/app/mypage/profile_modify/page.tsx
src/app/record/detail/[id]/MissionRecordHeader.tsx
src/app/record/detail/[id]/edit/page.tsx
src/app/record/detail/empty/page.tsx
src/components/Header/Header.types.ts
src/components/Header/TextButtonHeader.tsx
src/components/Input/DropdownInput.tsx

TextButtonHeader 을 사용할때 text button으로 form에 대한 대이터를 제출하는 ui가 종종 보였습니다 (수정, 제출 등) 
제어 컴포넌트로 진행한다면 현재 구조로 구현하는데에 문제가 없지만, 
비제어 컴포넌트로 form 제출을 위해서는 button type과 form 등의 attribute 들을 header 컴포넌트를 사용하는 곳에서 넣어주어야하는 필요성이 생겼습니다.
ComponentProps<typeof Button> 의 타입 중에 이미 디자인적으로 정해져서 컴포넌트내에서 결정되거나 다른 prop으로 주입하고 있었던  타입들을 제외하고 넣을 수 있게 하였습니다. 
TextButtonHeader props 타입에 버튼에 대한 타입인 rightButtonProps 을 추가했습니다.
1. rightButtonProps 를 객체로 받는것이 좋은 구조인지 모르겠습니다. 
처음에는 
```ts
export interface TextButtonHeaderType extends HeaderBaseType, Omit<ComponentProps<typeof Button>, 'children' | 'variant' | 'size'> {
rightAction: 'text-button';
rightButtonText?: string;
onButtonClick?: () => void;
rightButtonDisabled?: boolean;
}
```
로 모두 열었지만 header 에 관련된 props 와 button에 관련된 props가 섞이는게 헷갈릴수도 있겠다 싶어서 객체로 묶어서 주입하도록 …

:sparkles: TextButtonHeaderType 에 rightButtonProps 타입 추가

---

src/components/Input/Input.stories.ts
src/components/Input/Input.types.ts
src/components/Input/NormalButtonInput.tsx
src/components/Input/NormalInput.tsx

- NormalButtonInput, NormalInput 에서 value type optional이 아니여서 비제어 컴포넌트로 form을 만들지 못하는 문제가 있었습니다. 
- NormalButtonInput 컴포넌트에서 중복수정 로직이 있는 것보다는 컴포넌트 바깥에서 다루는게 좋을 것 같아서 수정했습니다.
- NormalButtonInput에 대한 스토리가 없어서 추가하였습니다.
-  NormalButtonInput, NormalInput의 value를 optional로 변경
- [NormalButtonInput props에 onTextButtonClick 추가](https://github.com/depromeet/10mm-client-web/commit/18a785a429ea9e23f4b4038b934a51a701a5a8b0)
- input 에 해당하는 라벨을 나타내는 텍스트들을 label 태그로 변경하였습니다. 
- input 컴포넌트 width 100% 변경
- 컴포넌트 width를 100% 로 변경하여도 아래 뷰에서 크게 깨지지는 않았으나 혹시 우려되는 점있으시면 리
뷰 남겨주세요

[Design] input component 수정

---

next.config.js
src/apis/auth.ts
src/apis/instance.api.ts
src/app/auth/login/page.tsx
src/app/auth/nickname/page.tsx
src/app/auth/signin/page.tsx
src/app/auth/signup/page.tsx
src/app/mypage/LogoutDialog.tsx
src/components/Input/NormalButtonInput.tsx
src/constants/router.ts
src/middleware.ts
src/services/auth/actions.ts

#32 
- 임시 로그인 페이지 
- 회원가입 페이지
- 닉네임 입력 페이지
- 로그인시 cookie 에 atk rtk 모두 저장
- 회원가입시 cookie 에 atk rtk 모두 저장
- 토큰 없을 시 middleware 에서 redirect
구현 해야하는 것 
- 로그인 화면 UI 조금 손봐야해요
- 로그아웃 기능 
- missions api 리스폰스 달라졌는데 그거 적용해야해요
- sever response type 일괄 처리  (data.data)
- sever action (use sever) 을 사용하기 위해서 experimental :  { severAction : true } 옵션 추가하였습니다 
- 미들웨어에서 리다이렉트하는 방법 중에 놓치는게 있다면 알려주세요 
현재 토큰 저장과 사용에는 문제없슴을 확인했습니다 이어서 로그아웃 바로 구현하겠습니다 (개발하는데는 문제없어서 PR생성합니다)
https://nextjs.org/docs/app/building-your-application/routing/middleware
https://react.dev/reference/react/use-server

[Task] 임시 로그인 구현

---

src/app/mission/new/MissionRegistration.tsx
src/components/Input/Input.types.ts
src/components/Input/NormalInput.tsx

- 미션 생성 페이지의 디스크립션 영역을 제거했습니다
- 첨부한 영상과 같이 Input 우측 하단의 글자수 세기 영역이 디자인 시스템과 다르게 글자를 입력해야 보이는 부분을 수정했습니다.
https://github.com/depromeet/10mm-client-web/assets/67476544/9c72dbef-03bb-43c6-8e5b-72657521c829

[Fix] 미션 생성 페이지 수정

---

src/apis/member.ts
src/app/auth/nickname/page.tsx
src/app/mypage/profile_modify/page.tsx
src/components/Input/Input.stories.ts
src/components/Input/Input.types.ts
src/components/Input/NormalButtonInput.tsx
src/hooks/useNickname.ts

closed #320 
- 프로필 수정 페이지에서 닉네임 중복체크 기능을 구현했습니다.
-  red.red500이 value.length 에도 들어가있어서 수정했습니다.
- 뮤테이션 성공 시 디스크립션을 띄워주는데 현재 컬러가 text.tertiary 입니다. 현재 profile_modify/page.tsx에서 validNickname 상태로 닉네임의 사용 가능 여부를 나타내는데, 이 상태를 가지고 normal-button Input 에서 컬러 값을 바꾸는 방식이 맞는지 모르겠습니다. 코멘트 주시면 수정해보겠습니다!

[Feat] 중복 체크기능 구현

---

src/apis/record.ts
src/app/mission/[id]/detail/MissionCalender/MissionCalendar.tsx

뒤로가기 할때 아래와 같은 이슈가 있어서 useSuspense query 대신 useQuery 로 변경

fix : useSuspense query 대신 useQuery 로 변경

---

src/components/Thumbnail/Thumbnail.tsx

썸네일 url이 서버 에러 대응으로 null로 바꿔서 보여주던 이슈 변경합니다

fix : Thumbnail.tsx image url null 처리 복구

---

src/app/home/FollowSummary.tsx
src/app/level/guide/Character.tsx
src/app/level/guide/GrowthLevel.tsx
src/app/level/guide/page.tsx
src/components/Banner/CardLevel.stories.tsx
src/components/Banner/CardLevel.tsx
src/components/Level/LockedCharacter.tsx
src/components/LevelStatus/LevelStatus.tsx
src/constants/style/gradient.ts
src/constants/style/text.ts

- lock 되어있는 캐릭터들을 두군데에서 정도 사용하는데, 이를 하나의 컴포넌트로 재사용하고 싶었음. (이후에도 쉽게 추가할 수 있었으면 해서)
- 디자인 시스템에 Banner/CardLevel 이라는 컴포넌트를 구현하고, 이를 재사용해 여러 컴포넌트를 구현
- CardLevel 스토리북에 추가
- Locked Character 리팩토링 (화면 유지)
- gradient border css 구현, cva로 만들어 bg를 선택할수 있도록 구현

[Feat] CardLevel 컴포넌트 생성

---

src/components/Input/NormalButtonInput.tsx

- NormalButtonInput.tsx의 width를 변경했습니다.
- normal-button을 사용하는 닉네임 설정 페이지도 같이 수정됐습니다.
**As-is**
**To-be**

[Fix] 중복확인 버튼 위치 수정

---

src/apis/member.ts
src/apis/schema/member.ts
src/app/mypage/profile_modify/page.tsx
src/hooks/useImage.ts

마이페이지 이미지 수정시 이미지 파일 확장자를 url에서 파싱해서 보내는게 아닌 서버에서 명시적으로 보낸 데이터로 수정한다
관련 슬랙 : https://depromeet14th.slack.com/archives/C06C1271G56/p1706229449971729

fix : 이미지의 확장자를 서버에서 받아온 데이터로 보내준다

---

src/app/mission/[id]/stopwatch/index.hooks.ts
src/app/mission/[id]/stopwatch/page.tsx

관련 슬랙 : https://depromeet14th.slack.com/archives/C06C1271G56/p1706453020931209
안드로이드 웹뷰에서  history.pushState(null, '', location.href); 로직이 적용되지 않아서 hotfix 합니다
제가 이해한게 맞는지 한번 체크해주세요 @sumi-0011

fix : pushstate props null 대신 빈객체로 변경

---

src/app/guest/mission/stopwatch/page.tsx
src/app/mission/[id]/stopwatch/page.tsx
src/app/profile/[id]/ProfileContent.tsx
src/components/Banner/Banner.stories.ts
src/components/Banner/Banner.stories.tsx
src/components/Banner/Banner.tsx
src/components/Banner/Banner.types.ts
src/components/Banner/CardBanner.tsx
src/components/Banner/GraphicBanner.tsx
src/components/Banner/ListBanner.tsx
src/components/Banner/ListLevelBanner.tsx
src/components/Stopwatch/Stopwatch.tsx
src/components/Stopwatch/StopwatchContainer.tsx

closed #430
- 스톱워치 페이지에서 그라데이션이 잘리는 문제를 수정했어요. 
- Banner 컴포넌트 디자인 변경사항을 수정하였어요. 
스톱워치 페이지에서 그라데이션이 잘리는 문제는, 
스톱워치 컴포넌트를 감싸는 wrapper에서 overflow hidden을 해주고 있어 box-shadow 가 잘리는 문제였어요. 
overflow hidden을 걸어준 이유 는 아래 스크린샷에서 확인할 수 있는데요, 
위와 같이 사진을 animation rotate로 돌리는데, 사진이 돌아가면서 화면에 넘치는 문제가 있었어요. 
화면에 넘쳐서 스크롤이 생기거나, 모바일에서는 옆에 흰 공간이 생기는 버그가 있었습니다. 
이 버그를 핫 픽스하면서 overflow:hidden을 걸어주었는데, box-shadow의 범위가 넓다보니 잘리는 문제가 생긴것이죠. 
기존에는 그라데이션 사진을 추출받아 사용하였는데, 이 방법을 사용하니 잘리는 문제를 해결하기가 어려웠어요, 
그래서 **그라데이션과 box-shadow 등등을 아예 css로 추가하는 방법**을 사용했습니다. (레이어 분리를 @지우 언니가 도와주었어요)
돌아가야하는 레이어에만 rotate animation을 걸고, 돌아가는 레이어 위에 한 겹을 감싸 overflow:hidden을 걸어주어 화면에 넘치지 않도록 하였어요 
box-shadow의 경우에는 돌아가지 않아도 되어 overflow:hidden을 걸어주지 않아도 되었습니다. 
css로 구현한 그라데이션 border가 조금 쨍한가? 🤔 싶었는데 다들 괜찮아 보이신다고 하네요 
이상해보이면 @지우 언니가 그때 이야기 …

[Hotfix] 스톱워치 페이지에서 그라데이션이 잘리는 문제 수정

---

src/components/MonitoringInitializer.tsx

- 제니퍼 프론트라는 모니터링 툴을 부착했어요.  (무료임)
- 세부 설정은 이후에 할 예정입니다 
저희 팀 구글 계정으로 
https://front.jennifersoft.com/#/app/206ba114/dashboard/overview?dateFilterType=hour&hourFilter=3600 이 페이지를 들어가면 대시보드를 확인하 실 수 있어요. 
로컬에서는 테스트 완료하였답니다. 👍
- https://vroomfan.tistory.com/47

제니퍼 프론트 모니터링 툴 추가

---

src/apis/follow.ts
src/apis/record.ts
src/apis/schema/member.ts
src/app/guest/mission/stopwatch/page.tsx
src/app/home/FollowContent.tsx
src/app/home/FollowSummary.tsx
src/app/mission/[id]/detail/MissionCalender/MissionCalendar.tsx
src/app/mission/[id]/detail/MissionCalender/MissionCalendar.utils.ts
src/app/mission/[id]/detail/MissionHistoryBanner/MissionHistoryBannerApi.tsx
src/app/mission/[id]/detail/MissionHistoryTab.tsx
src/app/mission/[id]/stopwatch/page.tsx
src/app/record/[id]/detail/HistoryThumbnail.tsx
src/app/record/[id]/page.tsx
src/app/search/page.tsx
src/components/AppBarBottom/AppBarBottomVIew.tsx
src/components/Header/Header.stories.tsx
src/components/Header/Header.tsx
src/components/Header/Header.types.ts
src/components/Header/HeaderBase.tsx
src/components/Header/IconHeader.tsx
src/components/Header/IconMenuHeader.tsx
src/components/Header/RightComponentHeader.tsx
src/components/ListItem/TwoLineListItem.tsx
src/components/Stopwatch/StopwatchContainer.tsx
src/components/Thumbnail/Thumbnail.tsx
src/components/Thumbnail/Thumbnail.types.ts

- 2,8번 제외 완
- 스톱워치 반갈죽 나는 이슈 해결
- 친구 프로필 프사 사이즈 수정 및 프사 이미지 추가
- 친구 미션 화면 UI가 디자인과 다른 부분 수정
- 미션 인증 이미지 업로드 시 프리뷰 짜부 이슈 해결
- [이미지 짜부 이슈 ](https://www.notion.so/depromeet/6f38352117bf450a84cc0816187565d5?v=0095167d334d4a08b4131127717a528a&p=e6bf00495ae9425db644832a2777100e&pm=s)

[Fix] QA 수정사항 반영 및 디자인 시스템 수정사항 반영

---

src/app/mission/[id]/detail/MissionCalender/MissionCalendar.utils.ts

closed #443
- 미션 캘린더뷰 라우팅 수정
- 닉네임 trim() 설정 [b26312b](https://github.com/depromeet/10mm-client-web/pull/442/commits/b26312b0744ddfe32da9c58a45d5ae45b6b6f50a)
(이거는 이미 devlop 에 머지 되었는데 혼선을 막기위해 여기에 기록합니다)
https://github.com/depromeet/10mm-client-web/assets/68339352/0d8b9694-ba16-45b4-a028-aa1a305a522c

[Fix] 미션캘린더 뷰에서 오늘 이후의 날짜는 라우팅 되지 않는다

---

src/app/mission/[id]/stopwatch/page.tsx
src/constants/storage.ts
src/hooks/mission/stopwatch/useStopwatch.ts
src/utils/storage/progressMission.ts

- 앱이 아닌 웹뷰에서 실행하다 보니 백그라운드에서 타이머가 잘 돌아가지 않는 문제가 있었어요
- 백그라운드에서도 타이머가 돌아갈 수 있도록 수정하였습니다.

[Feat] 백그라운드에서도 타이머가 돌아갈 수 있도록

---

src/hooks/useNickname.ts

close #454
- nickname 입력시 공백은 입력되지 않게한다 
- 중복확인시 validate 한 닉네임만 사용가능한 닉네임으로 처리한다

[FIX] 닉네임이 공백으로 수정 가능한 이슈

---

src/components/Tab/FullTab.tsx
src/components/Tab/FullTabParts.tsx
src/components/Tab/Tab.stories.tsx
src/components/Tab/Tab.types.ts

- 팔로우/팔로잉 페이지에서 사용되는 FullTabComponent를 구현하였어요.
- 기존에 있는 Tab컴포넌트의 로직을 재사용하였습니다.

feat: full tab component 생성

---

src/app/mission/[id]/detail/MissionCalender/MissionCalendar.tsx
src/app/mission/[id]/detail/MissionCalender/MissionCalendar.utils.ts
src/app/mission/[id]/detail/MissionHistoryBanner/MissionHistoryBannerApi.tsx
src/app/mission/[id]/detail/MissionHistoryTab.tsx
src/hooks/useCalendar.ts
src/hooks/useQueryParams.ts
src/hooks/useSearchParamState.ts

closed #468
- useCalendar 훅 구현
- query params 상태를 set 과 get할수 있는 useQueryParams 훅 구현 
- 친구 미션 상세 와 내 미션 상세 페이지 캘린더에서 이전 달을 볼 수 있게 변경하였습니다.
https://github.com/depromeet/10mm-client-web/assets/68339352/51256bbd-dfd0-49a7-b9e3-b443adc6833b
피그마 : https://www.figma.com/file/waOSgkTYJKQdMHXnGPlOum/%5BDEV%5D-Design-Guide?type=design&node-id=4467-55942&mode=design&t=bxPzMOxk49mU79Eu-11
관련 슬랙 : https://depromeet14th.slack.com/archives/C0647U2UG05/p1707054903589829

[FEAT] 이전 달의 미션 캘린더 정보를 볼 수 있다. 

---

src/app/home/FollowList.tsx
src/app/home/FollowMissionList.tsx
src/app/home/FollowSummary.tsx
src/app/home/MissionInnerList.tsx
src/app/home/ProfileItem.tsx
src/app/mission/[id]/detail/MissionHistoryBanner/MissionHistoryBanner.tsx
src/app/mission/[id]/follow/page.tsx
src/app/mypage/MyProfile.tsx
src/app/profile/[id]/FollowButton.tsx
src/app/profile/[id]/ProfileContent.tsx
src/app/profile/[id]/follows/FollowingList.tsx
src/app/profile/[id]/follows/page.tsx
src/app/record/[id]/page.tsx
src/app/record/success/layout.tsx
src/app/search/page.tsx
src/components/BottomDim/BottomDim.tsx
src/components/Button/GradientTextButton.tsx
src/components/Graph/LevelProgressBar.tsx
src/components/ListItem/Follow/MemberItem.tsx
src/components/Motion/StaggerWrapper.tsx
src/components/SearchBar/SearchBar.tsx
src/components/SnackBar/SnackBar.types.ts
src/components/SnackBar/SnackBarOverlay.tsx
src/hooks/query/useMutationHandleError.ts

- 여러가지 마이너 스타일 & 버그사항 & 개선사항을 추가하였어요. 
- 자세한 내용은 커밋 기록을 확인 부탁드립니다.

[Fix] 여러가지 수정사항 반영

---

src/apis/auth.ts
src/app/auth/kakaoCallback/page.tsx
src/app/auth/login/page.tsx
src/app/home/AppBar.tsx
src/app/home/FollowList.tsx
src/app/home/FollowMissionList.tsx
src/app/home/FollowSummary.tsx
src/app/home/MissionList.tsx
src/app/level/guide/page.tsx
src/app/mission/[id]/detail/MissionCalender/MissionCalendar.tsx
src/app/mypage/MyProfile.tsx
src/app/mypage/page.tsx
src/app/profile/[id]/FollowButton.tsx
src/app/profile/[id]/ProfileContent.tsx
src/app/result/page.tsx
src/components/AppBarBottom/AppBarBottomVIew.tsx
src/components/ListItem/Follow/MemberItem.tsx
src/constants/eventLog.ts

event logging 추가
- 이벤트 로깅 추가한 부분 
바텀 앱바 클릭 :  'click/tab'
결과 페이지 레벨 가이드 버튼 : 'click/levelGuide'
레벨 페이지 레벨 아이콘 클릭 :'click/level'
마이페이지 수정 버튼 : 'click/edit'
마이페이지 세팅 버튼 : 'click/setting'
마이페이지 레벨 배너 버튼 : 'click/levelBanner'
마이페이지 팔로우 리스트 버튼 : 'click/followFollow'
팔로우 프로필 팔로우 버튼 : 'click/followButton'
팔로우 리스트 팔로우 버튼 : 'click/followButton'
더 추가했으면 좋겠는 부분 알려주시면 추가하겠습니다.
- 로그인 시에 memberId를 서버에서 받아와 각 이벤트 logging 에 identify 를 실행하려합니다. 관련 로직 점검해주세요! cc @woobottle 
서버에서 memberId를 받기로 했습니다 
관련 슬랙 :  https://depromeet14th.slack.com/archives/C06C1271G56/p1707413630609489

[Feat] event logging 추가

---

src/app/profile/[id]/FollowButton.tsx
src/app/profile/[id]/page.tsx
src/components/Button/Button.tsx
src/components/Button/GradientTextButton.tsx
src/components/ListItem/Follow/MemberItem.tsx

- 팔로우/팔로잉 버튼을 연속으로 클릭시, 중복으로 API를 호출하여 에러 토스트가 뜨는 문제가 있었어요. 
- 팔로우/팔로잉 버튼을 누른 후 API가 호출되는 동안 버튼의 클릭을 막기위해 버튼에 blocked props를 추가하였습니다. 
- 단순히 팔로우 API의 pending 기간을 기다리는 것 뿐만 아니라, 이어지는 동작인 팔로우 리스트 refetch를 같이 기다려야 원하는 기능이 동작했어요. !!!

[Fix] Button Blocked 추가 & 프로필 팔로우/팔로잉 버튼 API 중복 호출 수정

---

src/app/record/[id]/page.tsx

closed #507 
- 미션 인증 submit 버튼을 여러번 클릭 시 API 중복 호출로 인해 에러 토스트가 뜨는 문제가 발생
- 기존의 대처 (isPending)으로 되지 않은 이유는, API 호출 후에 라우팅이 되기 전 사이에 버튼 클릭이 일어나서 발생한 것으로 추정
- sumit후 라우팅이 될 때 까지 loading으로 기다림, 
- 만약 오류가 발생했으면 loading을 풀어서 다른 동작을 수행하도록 함

[Fix] 인증 실패 메시지 뜨는 문제 수정

---

src/components/Graph/LastLevelGraph.tsx
src/components/Graph/PastLevelGraph.tsx

closed #514
"성공적으로 레벨을 완수했어요!" => "레벨업에 성공했어요!"
로 무슨무슨 이유로 텍스트 수정

:art: 레벨관련 문구 비문이슈로 수정

---

src/app/home/FollowMissionList.tsx
src/app/home/MissionInnerList.tsx

closed #520 
- 홈에서 뜨는 미션 리스트들 그냥 기존처럼 애니메이션 없이 바로 뜨는 방향으로 수정해달라는 @채연의 요청사항
- 검색페이지와 동일한 0.02 delay로 수정
- 팔로워 미션 리스트에서는 스켈레톤이 거슬린다고 생각했어요. 그래서 팔로워 미션리스트에서만 제거하였습니다. 
- 내 미션 리스트에서는 스켈레톤을 유지하였습니다 -> 종종 딜레이가 걸리거나 오류가 발생하는 것을 봤기 떄문입니당.

[Design] 홈에서 뜨는 미션 리스트들 그냥 기존처럼 애니메이션 없이 바로 뜨는 방향으로 수정

---

src/app/record/success/page.tsx
src/components/AppBarBottom/AppBarBottomVIew.tsx
src/constants/nativeCustomEvent.ts
src/utils/nativeMethod.ts

closed  #526
탭 변경 시 햅틱 추가, 미션 인증 페이지 진입 시 진동 발생시키기
진동 => 휴대폰을 진동해버림
햅틱 => 뾱하면서 진동 약한 버전

:art: 햅틱/진동 추가

---

src/app/level/guide/page.tsx
src/components/Banner/CardBanner.tsx

closed #464 
- 잠금의 경우에도 현재 레벨이라는 텍스트가 보이는 부분을 수정하였어요.

[Fix] 잠금의 경우에도 현재 레벨이라는 텍스트가 보이는 부분을 수정

---

src/apis/instance.api.ts
src/app/auth/kakaoCallback/page.tsx
src/app/auth/login/page.tsx
src/app/global.d.ts
src/app/mypage/page.tsx
src/app/profile/[id]/page.tsx
src/hooks/useAuth.ts
src/utils/common.ts
src/utils/index.ts

- 프로필 링크복사기능
- 다른 path로 들어왔을때 로그인후 해당 path로 리다이렉트
- 카카오톡 로그인의 state 의 속성으로 callback url에서 state query prams를 같이 받아오는 로직으로 풀었습니다.
- 네이티브에서 애플로그인 / 카카오로그인은 대응은 해두었지만 제대로 동작하는지 확인은 하지 않았습니다. (네이티브에서 기존처럼 로그인하는데 문제는 없을 듯합니다) 나중에 딥링크를 붙였을때 로직을 생각해봐야겠어요
우선은 웹 동작 기준으로 대응했다고 보시면 될 것 같습니다!
피그마에서는 쉐어 아이콘으로 되어있었는데 뭔가 쉐어아이콘은 네이티브 쉐어가 떠야할 것 같아서 클립 아이콘으로 변경했습니다
(디자인 팀과 이야기 필요)
https://github.com/depromeet/10mm-client-web/assets/68339352/85d77d88-f9de-48f3-9bd3-05722ba089e1
https://github.com/depromeet/10mm-client-web/assets/68339352/3919506f-db07-45e2-8cfb-f2c25a0744f6
스크린샷
https://developers.kakao.com/docs/latest/ko/kakaologin/js#login-info

[Feat] 프로필 링크 복사 기능

---

src/components/Header/HeaderBase.tsx

바텀시트가 열릴때 head가 보임
header의 zindex를 변경했습니다. (꼭 100이여야하는 이유가 있다면 알려주세요)
라이브러리로 사용하고 있는 react-spring-bottom-sheet  에서 zIndex를 변경하기 까다로워서 header의 zindex를 낮추는 방향으로 수정하였습니다.

fix : header zindex 수정

---

src/apis/reaction.ts
src/apis/schema/feed.ts
src/app/feed/FeedItem.tsx
src/app/home/FollowContent/FollowMissionList.tsx
src/app/home/FollowContent/MyMissionInnerList.tsx
src/app/home/FollowContent/MyMissionList.tsx
src/app/home/FollowContent/index.tsx
src/components/AppBarBottom/AppBarBottomVIew.tsx
src/components/Icon/TrashcanIcon.tsx
src/components/Icon/index.tsx
src/components/ListItem/TwoLineListItem.tsx
src/components/MissionList/ReactionLinkItem.tsx
src/components/MissionList/index.tsx
src/components/ReactionBar/MyReactionBar/MyReactionBar.tsx
src/components/ReactionBar/OtherReactionBar/OtherReactionBar.tsx
src/components/ReactionBar/ReactionBottomSheet.tsx
src/components/SnackBar/SnackBarOverlay.tsx
src/constants/eventLog.ts

- 리액션 리스트를 Home에서 확인할 수 있도록 하였습니다 (my/follower mission list)
- 리액션 삭제 기능을 추가하였습니다. 
- 리액션이 하나도 없는데, 리액션 바텀시트를 열려고 하면 응원을 해야한다는 snackbar를 띄웠습니다. 
- 리액션 바텀시트의 윗부분을 클릭하면, 뒤에 부분이 눌리는 문제가 있었는데 backdrop을 하나 더 둠으로써 이벤트 버블링을 막았습니다. 
- 피드 부분에 날짜가 잘못들어간 부분을 @윤범과 이야기 해서 수정하였습니다.

[Feat] Reaction 추가기능 반영

---

src/hooks/mission/stopwatch/useStopwatch.ts
src/utils/storage/progressMission.test.ts
src/utils/storage/progressMission.ts

- progressMission 이라는 util 함수의 테스트를 진행했어요. 
- 해당 util은 스톱워치 페이지에서 스톱워치의 시간이 백그라운드에서도 흐르는 것처럼 보이기 위해 사용하는 로직이예요. 
- progressMission에 관련된 모든 로직에 대해 테스트 코드 작성을 완료한 것은 아니며, 
- 주요 로직인 mission을 시작할 때 미션의 데이터를 저장하는 것, 그리고 미션 진행 시간을 계산하는 로직만을 우선적으로 테스트해보았습니다.

[Test] ProgressMission util Test

---

src/apis/feed.ts
src/apis/getQueryKey.ts
src/app/feed/FeedList.tsx
src/app/feed/FeedSection.tsx
src/hooks/useIntersect.ts
src/styles/position.ts

closed #616 
- useInfiniteQuery 를 이용해 무한 스크롤을 구현하였어요. 
- observer를 사용하는 hook은 공통적으로 사용될 거라고 생각해 hooks 폴더에 위치시켰습니다. 
- 무한스크롤 로직과 꼬이는 일이 있어,  "초기에 팔로워의 피드가 없는 상태라면, 전체 피드로 변경" 하는 기능을 잠시 넣어두었습니다. (중요하지 않은 것이고, 다른 방향으로 개선해보면 좋을 것 같아요
- 
- https://oliveyoung.tech/blog/2023-10-04/useInfiniteQuery-scroll/

Feed에 페이지네이션 적용

---

src/apis/notifications.ts
src/app/mission/[id]/stopwatch/ButtonSection.tsx

BG
미션을 시작하고 나서 까먹고 인증을 안한다거나 60분이 넘어가면 무슨무슨 에러가 발생하는 경우가 간헐적으로 있었다
시작 후 10분 뒤에 알림을 주어 인증이 가능하게 끔 유도하자
Task
미션 시작하고 10분 뒤에 알림을 주어 이제부터 미션 인증이 가능하다고 알려준다
- 서버 API 호출
- 기본값 10분 => 600 s

10분뒤에 인증 가능 알림

---

src/components/ErrorPage.tsx
src/pages/_app.page.tsx

점검 페이지 생성 및 app에 적용
